In [1]:
import numpy as np

In [2]:
np.array([1, 2, 3, 4])

array([1, 2, 3, 4])

In [3]:
a = np.array([1, 2, 3, 4])

In [4]:
b = np.array([0, .5, 1, 1.5, 2])

In [5]:
a[0]

1

In [6]:
a[1]

2

In [7]:
a[0:]

array([1, 2, 3, 4])

In [8]:
a[1:3]

array([2, 3])

In [9]:
a[1:-1]

array([2, 3])

In [10]:
a[::2]

array([1, 3])

In [11]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [13]:
b[0]

0.0

In [14]:
b[2]

1.0

In [15]:
b[-1]

2.0

In [16]:
b[[0, 2, -1]]

array([0., 1., 2.])

In [17]:
a

array([1, 2, 3, 4])

In [18]:
a.dtype

dtype('int32')

In [19]:
b

array([0. , 0.5, 1. , 1.5, 2. ])

In [20]:
b.dtype

dtype('float64')

In [21]:
np.array([1, 2, 3, 4], dtype=np.float)

C:\Users\German\AppData\Local\Temp/ipykernel_8800/217965920.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.array([1, 2, 3, 4], dtype=np.float)


array([1., 2., 3., 4.])

In [22]:
np.array([1, 2, 3, 4], dtype=np.int8)

array([1, 2, 3, 4], dtype=int8)

In [23]:
c = np.array(['a', 'b', 'c'])

In [24]:
c.dtype

dtype('<U1')

In [25]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

In [26]:
A.shape

(2, 3)

In [27]:
A.ndim

2

In [28]:
A.size

6

In [29]:
B = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4],
        [3, 2, 1]
    ]
])

In [30]:
B

array([[[12, 11, 10],
        [ 9,  8,  7]],

       [[ 6,  5,  4],
        [ 3,  2,  1]]])

In [31]:
B.shape

(2, 2, 3)

In [32]:
B.ndim

3

In [33]:
B.size

12

In [34]:
C = np.array([
    [
        [12, 11, 10],
        [9, 8, 7],
    ],
    [
        [6, 5, 4]
    ]
])

C:\Users\German\AppData\Local\Temp/ipykernel_8800/548599459.py:1: VisibleDeprecationWarning: Creating an ndarray from ragged nested sequences (which is a list-or-tuple of lists-or-tuples-or ndarrays with different lengths or shapes) is deprecated. If you meant to do this, you must specify 'dtype=object' when creating the ndarray.
  C = np.array([


In [35]:
C.dtype

dtype('O')

In [36]:
C.shape

(2,)

In [37]:
C.size

2

In [38]:
type(C[0])

list

In [39]:
A = np.array([
    [1, 2, 3], 
    [4, 5, 6], 
    [7, 8, 9]  
])

In [40]:
A[1]

array([4, 5, 6])

In [41]:
A[1][0]

4

In [43]:
A[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
A[:, :2]

array([[1, 2],
       [4, 5],
       [7, 8]])

In [45]:
A[:2, :2]

array([[1, 2],
       [4, 5]])

In [46]:
A[:2, 2:]

array([[3],
       [6]])

In [47]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
A[1] = np.array([10, 10, 10])

In [49]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [ 7,  8,  9]])

In [50]:
A[2] = 99

In [51]:
A

array([[ 1,  2,  3],
       [10, 10, 10],
       [99, 99, 99]])

In [52]:
a = np.array([1, 2, 3, 4])

In [53]:
a.sum()

10

In [54]:
a.mean()

2.5

In [55]:
a.std()

1.118033988749895

In [56]:
a.var()

1.25

In [57]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [58]:
A.sum()

45

In [59]:
A.mean()

5.0

In [60]:
A.std()

2.581988897471611

In [61]:
A.sum(axis=0)

array([12, 15, 18])

In [62]:
A.sum(axis=1)

array([ 6, 15, 24])

In [63]:
A.mean(axis=0)

array([4., 5., 6.])

In [64]:
A.mean(axis=1)

array([2., 5., 8.])

In [65]:
A.std(axis=0)

array([2.44948974, 2.44948974, 2.44948974])

In [66]:
A.std(axis=1)

array([0.81649658, 0.81649658, 0.81649658])

In [67]:
a = np.arange(4)

In [68]:
a

array([0, 1, 2, 3])

In [69]:
a + 10

array([10, 11, 12, 13])

In [70]:
a * 10

array([ 0, 10, 20, 30])

In [71]:
a

array([0, 1, 2, 3])

In [72]:
a += 100

In [73]:
a

array([100, 101, 102, 103])

In [74]:
l = [0, 1, 2, 3]

In [75]:
[i * 10 for i in l]

[0, 10, 20, 30]

In [76]:
a = np.arange(4)

In [77]:
a

array([0, 1, 2, 3])

In [78]:
b = np.array([10, 10, 10, 10])

In [79]:
b

array([10, 10, 10, 10])

In [80]:
a + b

array([10, 11, 12, 13])

In [81]:
a * b

array([ 0, 10, 20, 30])

In [82]:
a = np.arange(4)

In [83]:
a

array([0, 1, 2, 3])

In [84]:
a[0]

0

In [85]:
a[-1]

3

In [86]:
a[[0, -1]]

array([0, 3])

In [87]:
a[[True, False, False, True]]

array([0, 3])

In [88]:
a

array([0, 1, 2, 3])

In [89]:
a >= 2

array([False, False,  True,  True])

In [90]:
a[a >= 2]

array([2, 3])

In [91]:
a.mean()

1.5

In [92]:
a[a > a.mean()]

array([2, 3])

In [93]:
a[~(a > a.mean())]

array([0, 1])

In [94]:
a[(a == 0) | (a == 1)]

array([0, 1])

In [95]:
a[(a <= 2) & (a % 2 == 0)]

array([0, 2])

In [96]:
A = np.random.randint(100, size=(3, 3))

In [97]:
A

array([[75, 50, 30],
       [69, 86, 96],
       [74,  3, 11]])

In [98]:
A[np.array([
    [True, False, True],
    [False, True, False],
    [True, False, True]
])]

array([75, 30, 86, 74, 11])

In [99]:
A > 30

array([[ True,  True, False],
       [ True,  True,  True],
       [ True, False, False]])

In [100]:
A[A > 30]

array([75, 50, 69, 86, 96, 74])

In [101]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

In [102]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [103]:
B = np.array([
    [6, 5],
    [4, 3],
    [2, 1]
])

In [104]:
B

array([[6, 5],
       [4, 3],
       [2, 1]])

In [105]:
A.dot(B)

array([[20, 14],
       [56, 41],
       [92, 68]])

In [112]:
np.random.normal(size=2)

array([ 0.75780518, -0.36111648])

In [111]:
np.random.random(size=2)

array([0.1690785 , 0.14267882])

In [113]:
np.random.rand(2, 4)

array([[0.72471162, 0.85998562, 0.46880453, 0.12011499],
       [0.39010606, 0.16389288, 0.13871646, 0.03344507]])

In [114]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [115]:
np.arange(5, 10)

array([5, 6, 7, 8, 9])

In [116]:
np.arange(0, 1, .1)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

In [117]:
np.arange(10).reshape(2, 5)

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [118]:
np.arange(10).reshape(5, 2)

array([[0, 1],
       [2, 3],
       [4, 5],
       [6, 7],
       [8, 9]])

In [119]:
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [120]:
np.linspace(0, 1, 20)

array([0.        , 0.05263158, 0.10526316, 0.15789474, 0.21052632,
       0.26315789, 0.31578947, 0.36842105, 0.42105263, 0.47368421,
       0.52631579, 0.57894737, 0.63157895, 0.68421053, 0.73684211,
       0.78947368, 0.84210526, 0.89473684, 0.94736842, 1.        ])

In [121]:
np.linspace(0, 1, 20, False)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [122]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [123]:
np.zeros((3, 3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [124]:
np.zeros((3, 3), dtype=np.int)

C:\Users\German\AppData\Local\Temp/ipykernel_8800/383259716.py:1: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.zeros((3, 3), dtype=np.int)


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [125]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [126]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [127]:
np.empty(5)

array([1., 1., 1., 1., 1.])

In [128]:
np.empty((2, 2))

array([[0.25, 0.5 ],
       [0.75, 1.  ]])

In [129]:
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [130]:
np.eye(3, 3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [131]:
np.eye(8, 4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [132]:
np.eye(8, 4, k=1)

array([[0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [133]:
np.eye(8, 4, k=-3)

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.],
       [0., 0., 0., 0.]])